apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels: 
    app: myapp
    type: frontend
spec:
  
  replicas: 5
  selector:
    matchLabels:
      type: front-end
  
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: app
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx 1.7.1    
