# apiVersion: v1
# kind: Pod
# metadata:
#   name: myapp-pod
#   labels:
#     app: my-app
#     type: front-end

# spec:
#   containers:
#     - name: nginx-container
#       image: nginx 1.25.3


##//https://www.sumologic.com/blog/kubernetes-deploy-postgres/

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    env: Test

spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "key1"
    operator: "Equal"
    effect: "NoSchedule"






# ##https://hub.docker.com/_/redis

# apiVersion: v1
# kind: Pod
# metadata:
#   name: testapp-redis
#   labels:
#     app: testapp-redis
#     type: cache
# spec:
#   containers:
#   - name: redis
#     image: redis


# kubectl taint nodes node1 key1=value1:NoSchedule

